//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:05:02 PM CEST 
//


package com.projectxml.accommodationunittype;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projectxml.accommodationunittype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projectxml.accommodationunittype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddAccommodationUnitTypeResponse }
     * 
     */
    public AddAccommodationUnitTypeResponse createAddAccommodationUnitTypeResponse() {
        return new AddAccommodationUnitTypeResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnitType }
     * 
     */
    public AccommodationUnitType createAccommodationUnitType() {
        return new AccommodationUnitType();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitTypesRequest }
     * 
     */
    public GetAccommodationUnitTypesRequest createGetAccommodationUnitTypesRequest() {
        return new GetAccommodationUnitTypesRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitTypesResponse }
     * 
     */
    public GetAccommodationUnitTypesResponse createGetAccommodationUnitTypesResponse() {
        return new GetAccommodationUnitTypesResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnitTypes }
     * 
     */
    public AccommodationUnitTypes createAccommodationUnitTypes() {
        return new AccommodationUnitTypes();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitTypeRequest }
     * 
     */
    public GetAccommodationUnitTypeRequest createGetAccommodationUnitTypeRequest() {
        return new GetAccommodationUnitTypeRequest();
    }

    /**
     * Create an instance of {@link RemoveAccommodationUnitTypeRequest }
     * 
     */
    public RemoveAccommodationUnitTypeRequest createRemoveAccommodationUnitTypeRequest() {
        return new RemoveAccommodationUnitTypeRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitTypeResponse }
     * 
     */
    public GetAccommodationUnitTypeResponse createGetAccommodationUnitTypeResponse() {
        return new GetAccommodationUnitTypeResponse();
    }

    /**
     * Create an instance of {@link AddAccommodationUnitTypeRequest }
     * 
     */
    public AddAccommodationUnitTypeRequest createAddAccommodationUnitTypeRequest() {
        return new AddAccommodationUnitTypeRequest();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitTypeRequest }
     * 
     */
    public UpdateAccommodationUnitTypeRequest createUpdateAccommodationUnitTypeRequest() {
        return new UpdateAccommodationUnitTypeRequest();
    }

}
