//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 07:55:21 PM CEST 
//


package ftn.xmlws.model;

import java.time.LocalDateTime;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import ftn.xmlws.dto.MessageDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Message_content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Seen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Sender" type="{http://booking.uns.ac.rs/users}User"/>
 *         &lt;element name="Reciever" type="{http://booking.uns.ac.rs/users}User"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/reservation}Reservation"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Datum_vreme" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageContent",
    "seen",
    "sender",
    "reciever",
    "id",
    "deleted",
    "reservation"
})
@XmlRootElement(name = "Message", namespace = "http://booking.uns.ac.rs/reservation")
@Entity
public class Message {

	
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlElement(name = "Id", namespace = "http://booking.uns.ac.rs/reservation")
    protected Long id;
    
    @XmlElement(name = "Message_content", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    protected String messageContent;
    
    @XmlElement(name = "Seen", namespace = "http://booking.uns.ac.rs/reservation")
    protected boolean seen;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Sender", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    protected User sender;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Reciever", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    protected User reciever;
    
    @XmlElement(name = "Deleted", namespace = "http://booking.uns.ac.rs/reservation")
    protected boolean deleted;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Reservation", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    protected Reservation reservation;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    //@XmlElement(name = "Accomodation", namespace = "http://booking.uns.ac.rs/accommodation", required = true)
    protected Accommodation accommodation;
    
    @Transient
    @XmlAttribute(name = "Datum_vreme")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumVreme;
    
    @Column(name = "Date_time")
	protected LocalDateTime dateTime;
    
    public Message() {
    	
    }
    
    public Message(MessageDTO m) {
    	this.messageContent = m.getMessageContent();
    	this.seen = m.isSeen();
    	this.deleted = false;
    	//this.sender = m.getSender();
    	//resiver je uvek u ovom trenutku null
    	//this.reservation = m.getReservation();
    	//this.accommodation = m.getAccommodation();
    	this.dateTime = LocalDateTime.now();
    }

    /**
     * Gets the value of the messageContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * Sets the value of the messageContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageContent(String value) {
        this.messageContent = value;
    }

    /**
     * Gets the value of the seen property.
     * 
     */
    public boolean isSeen() {
        return seen;
    }

    /**
     * Sets the value of the seen property.
     * 
     */
    public void setSeen(boolean value) {
        this.seen = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setSender(User value) {
        this.sender = value;
    }

    /**
     * Gets the value of the reciever property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getReciever() {
        return reciever;
    }

    /**
     * Sets the value of the reciever property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setReciever(User value) {
        this.reciever = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link Reservation }
     *     
     */
    public Reservation getReservation() {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reservation }
     *     
     */
    public void setReservation(Reservation value) {
        this.reservation = value;
    }

    /**
     * Gets the value of the datumVreme property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVreme() {
        return datumVreme;
    }

    /**
     * Sets the value of the datumVreme property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVreme(XMLGregorianCalendar value) {
        this.datumVreme = value;
    }

	public Accommodation getAccommodation() {
		return accommodation;
	}

	public void setAccommodation(Accommodation accommodation) {
		this.accommodation = accommodation;
	}

	public LocalDateTime getDateTime() {
		return dateTime;
	}

	public void setDateTime(LocalDateTime dateTime) {
		this.dateTime = dateTime;
	}

}
