//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 05:05:02 PM CEST 
//


package com.projectxml.accommodationunit;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projectxml.accommodationunit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projectxml.accommodationunit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAccommodationUnitsRequest }
     * 
     */
    public GetAccommodationUnitsRequest createGetAccommodationUnitsRequest() {
        return new GetAccommodationUnitsRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitRequest }
     * 
     */
    public GetAccommodationUnitRequest createGetAccommodationUnitRequest() {
        return new GetAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link AddAccommodationUnitRequest }
     * 
     */
    public AddAccommodationUnitRequest createAddAccommodationUnitRequest() {
        return new AddAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link AddAccommodationUnitResponse }
     * 
     */
    public AddAccommodationUnitResponse createAddAccommodationUnitResponse() {
        return new AddAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link RemoveAccommodationUnitRequest }
     * 
     */
    public RemoveAccommodationUnitRequest createRemoveAccommodationUnitRequest() {
        return new RemoveAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitsResponse }
     * 
     */
    public GetAccommodationUnitsResponse createGetAccommodationUnitsResponse() {
        return new GetAccommodationUnitsResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnits }
     * 
     */
    public AccommodationUnits createAccommodationUnits() {
        return new AccommodationUnits();
    }

    /**
     * Create an instance of {@link UpdateAccommodationUnitRequest }
     * 
     */
    public UpdateAccommodationUnitRequest createUpdateAccommodationUnitRequest() {
        return new UpdateAccommodationUnitRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationUnitResponse }
     * 
     */
    public GetAccommodationUnitResponse createGetAccommodationUnitResponse() {
        return new GetAccommodationUnitResponse();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link AccommodationUnitType }
     * 
     */
    public AccommodationUnitType createAccommodationUnitType() {
        return new AccommodationUnitType();
    }

}
