//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.25 at 10:49:35 PM CEST 
//


package ftn.xmlws.model;

import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;
import javax.xml.datatype.XMLGregorianCalendar;

import ftn.xmlws.dto.ReservationDTO;
import ftn.xmlws.miscellaneous.MyTypeConverter;


@Entity
public class Reservation {

	
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

	@Transient
    private XMLGregorianCalendar fromDate;
    
	@Column(name = "From_date")
	public Calendar getFromDateToCalendar() {
	    return new GregorianCalendar(fromDate.getYear(), fromDate.getMonth(), fromDate.getDay());
	}
	
	@Transient
    private XMLGregorianCalendar toDate;
    
	@Column(name = "To_date")
	public Calendar getToDateToCalendar() {
	    return new GregorianCalendar(toDate.getYear(), toDate.getMonth(), toDate.getDay());
	}
	
    private boolean confirmed;
    private boolean deleted;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private User guest;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private AccommodationUnit accommodationUnit;

    
    //@XmlElement(namespace = "http://booking.uns.ac.rs/reservation")
    //protected Reservation.Conversation conversation;
    //@XmlElement(name = "Comment_rate", namespace = "http://booking.uns.ac.rs/reservation")
    //protected Reservation.CommentRate commentRate;
    
    
    public Reservation() {}
    
    
    public Reservation(XMLGregorianCalendar fromDate, XMLGregorianCalendar toDate, boolean confirmed) {
		super();
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.confirmed = confirmed;
		this.deleted = false;
	}
    
    public Reservation(ReservationDTO res) {
		super();
		this.fromDate = MyTypeConverter.localDateToXMLGregorianCalendar(res.getFromDate());
		this.toDate = MyTypeConverter.localDateToXMLGregorianCalendar(res.getToDate());
		this.confirmed = res.isConfirmed();
		this.deleted = res.isDeleted();
	}


	/**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setToDate(XMLGregorianCalendar value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     */
    public void setConfirmed(boolean value) {
        this.confirmed = value;
    }


    /**
     * Gets the value of the accommodationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationUnit }
     *     
     */
    public AccommodationUnit getAccommodationUnit() {
        return accommodationUnit;
    }

    /**
     * Sets the value of the accommodationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationUnit }
     *     
     */
    public void setAccommodationUnit(AccommodationUnit value) {
        this.accommodationUnit = value;
    }

    /**
     * Gets the value of the guest property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public User getGuest() {
        return guest;
    }

    /**
     * Sets the value of the guest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGuest(User value) {
        this.guest = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


	public boolean isDeleted() {
		return deleted;
	}


	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}


	public void setId(Long id) {
		this.id = id;
	}


    

}
