//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.21 at 05:17:32 PM CEST 
//


package com.projectxml.periodprice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accommodationUnitId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="periodPriceDates" type="{http://www.projectXml.com/periodPrice}periodPriceDates"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accommodationUnitId",
    "periodPriceDates"
})
@XmlRootElement(name = "getPeriodPriceForMonthRequest")
public class GetPeriodPriceForMonthRequest {

    protected long accommodationUnitId;
    @XmlElement(required = true)
    protected PeriodPriceDates periodPriceDates;

    /**
     * Gets the value of the accommodationUnitId property.
     * 
     */
    public long getAccommodationUnitId() {
        return accommodationUnitId;
    }

    /**
     * Sets the value of the accommodationUnitId property.
     * 
     */
    public void setAccommodationUnitId(long value) {
        this.accommodationUnitId = value;
    }

    /**
     * Gets the value of the periodPriceDates property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodPriceDates }
     *     
     */
    public PeriodPriceDates getPeriodPriceDates() {
        return periodPriceDates;
    }

    /**
     * Sets the value of the periodPriceDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodPriceDates }
     *     
     */
    public void setPeriodPriceDates(PeriodPriceDates value) {
        this.periodPriceDates = value;
    }

}
