//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.21 at 05:17:32 PM CEST 
//


package com.projectxml.periodprice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projectxml.periodprice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projectxml.periodprice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPeriodPricesRequest }
     * 
     */
    public GetPeriodPricesRequest createGetPeriodPricesRequest() {
        return new GetPeriodPricesRequest();
    }

    /**
     * Create an instance of {@link GetPeriodPricesResponse }
     * 
     */
    public GetPeriodPricesResponse createGetPeriodPricesResponse() {
        return new GetPeriodPricesResponse();
    }

    /**
     * Create an instance of {@link PeriodPrices }
     * 
     */
    public PeriodPrices createPeriodPrices() {
        return new PeriodPrices();
    }

    /**
     * Create an instance of {@link AddPeriodPriceRequest }
     * 
     */
    public AddPeriodPriceRequest createAddPeriodPriceRequest() {
        return new AddPeriodPriceRequest();
    }

    /**
     * Create an instance of {@link PeriodPrice }
     * 
     */
    public PeriodPrice createPeriodPrice() {
        return new PeriodPrice();
    }

    /**
     * Create an instance of {@link AddPeriodPriceResponse }
     * 
     */
    public AddPeriodPriceResponse createAddPeriodPriceResponse() {
        return new AddPeriodPriceResponse();
    }

    /**
     * Create an instance of {@link RemovePeriodPriceRequest }
     * 
     */
    public RemovePeriodPriceRequest createRemovePeriodPriceRequest() {
        return new RemovePeriodPriceRequest();
    }

    /**
     * Create an instance of {@link GetPeriodPriceRequest }
     * 
     */
    public GetPeriodPriceRequest createGetPeriodPriceRequest() {
        return new GetPeriodPriceRequest();
    }

    /**
     * Create an instance of {@link GetPeriodPriceResponse }
     * 
     */
    public GetPeriodPriceResponse createGetPeriodPriceResponse() {
        return new GetPeriodPriceResponse();
    }

    /**
     * Create an instance of {@link UpdatePeriodPriceRequest }
     * 
     */
    public UpdatePeriodPriceRequest createUpdatePeriodPriceRequest() {
        return new UpdatePeriodPriceRequest();
    }

    /**
     * Create an instance of {@link GetPeriodPriceForMonthRequest }
     * 
     */
    public GetPeriodPriceForMonthRequest createGetPeriodPriceForMonthRequest() {
        return new GetPeriodPriceForMonthRequest();
    }

    /**
     * Create an instance of {@link PeriodPriceDates }
     * 
     */
    public PeriodPriceDates createPeriodPriceDates() {
        return new PeriodPriceDates();
    }

    /**
     * Create an instance of {@link GetPeriodPriceForMonthResponse }
     * 
     */
    public GetPeriodPriceForMonthResponse createGetPeriodPriceForMonthResponse() {
        return new GetPeriodPriceForMonthResponse();
    }

    /**
     * Create an instance of {@link AccommodationUnit }
     * 
     */
    public AccommodationUnit createAccommodationUnit() {
        return new AccommodationUnit();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AccommodationUnitType }
     * 
     */
    public AccommodationUnitType createAccommodationUnitType() {
        return new AccommodationUnitType();
    }

}
