//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.21 at 05:17:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.projectXml.com/periodPrice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.projectxml.periodprice;
