//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 11:32:40 PM CEST 
//


package com.projectxml.accommodation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accommodationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="accommodationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HOTEL"/&gt;
 *     &lt;enumeration value="MOTEL"/&gt;
 *     &lt;enumeration value="BED_AND_BREAKFAST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "accommodationType")
@XmlEnum
public enum AccommodationType {

    HOTEL,
    MOTEL,
    BED_AND_BREAKFAST;

    public String value() {
        return name();
    }

    public static AccommodationType fromValue(String v) {
        return valueOf(v);
    }

}
