//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.11 at 08:30:50 PM CEST 
//


package com.projectxml.accommodation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projectxml.accommodation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projectxml.accommodation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RemoveAccommodationRequest }
     * 
     */
    public RemoveAccommodationRequest createRemoveAccommodationRequest() {
        return new RemoveAccommodationRequest();
    }

    /**
     * Create an instance of {@link AddAccommodationRequest }
     * 
     */
    public AddAccommodationRequest createAddAccommodationRequest() {
        return new AddAccommodationRequest();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link UpdateAccommodationRequest }
     * 
     */
    public UpdateAccommodationRequest createUpdateAccommodationRequest() {
        return new UpdateAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link AddAccommodationResponse }
     * 
     */
    public AddAccommodationResponse createAddAccommodationResponse() {
        return new AddAccommodationResponse();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

}
