//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 08:02:55 PM CEST 
//


package com.projectxml.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accommodationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="accommodationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HOTEL"/>
 *     &lt;enumeration value="MOTEL"/>
 *     &lt;enumeration value="BED_AND_BREAKFAST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "accommodationType")
@XmlEnum
public enum AccommodationType {

    HOTEL,
    MOTEL,
    BED_AND_BREAKFAST;

    public String value() {
        return name();
    }

    public static AccommodationType fromValue(String v) {
        return valueOf(v);
    }

}
