//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 10:21:11 PM CEST 
//


package com.projectxml.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import ftn.xmlws.dto.MessageDTO;


/**
 * <p>Java class for message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sender" type="{http://www.projectXml.com/message}user"/>
 *         &lt;element name="reciever" type="{http://www.projectXml.com/message}user"/>
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="reservation" type="{http://www.projectXml.com/message}reservation"/>
 *         &lt;element name="accommodation" type="{http://www.projectXml.com/message}accommodation"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message", propOrder = {
    "messageContent",
    "seen",
    "sender",
    "reciever",
    "deleted",
    "reservation",
    "accommodation",
    "id"
})
public class Message {


	@XmlElement(required = true)
	protected String messageContent;
	protected boolean seen;
	@XmlElement(required = true)
	protected com.projectxml.mojuser.User sender;
	@XmlElement(required = true)
	protected com.projectxml.mojuser.User reciever;
	protected boolean deleted;
	@XmlElement(required = true)
	protected com.projectxml.reservation.Reservation reservation;
	@XmlElement(required = true)
	protected com.projectxml.accommodation.Accommodation accommodation;
	protected Long id;
    
    public Message() {
	}

	public Message(MessageDTO msg) {
		if(msg.getAccommodation() != null)
			this.accommodation = new com.projectxml.accommodation.Accommodation(msg.getAccommodation());
		this.id = msg.getId();
		this.reservation = new com.projectxml.reservation.Reservation(msg.getReservation());
		this.deleted = msg.isDeleted();
		this.sender = new com.projectxml.mojuser.User(msg.getSender());
		
		if(msg.getReciever()!= null)
			this.reciever = new com.projectxml.mojuser.User(msg.getReciever());
		this.messageContent = msg.getMessageContent();
		this.seen = msg.isSeen();
	}

	/**
	 * Gets the value of the messageContent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMessageContent() {
		return messageContent;
	}

	/**
	 * Sets the value of the messageContent property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMessageContent(String value) {
		this.messageContent = value;
	}

	/**
	 * Gets the value of the seen property.
	 * 
	 */
	public boolean isSeen() {
		return seen;
	}

	/**
	 * Sets the value of the seen property.
	 * 
	 */
	public void setSeen(boolean value) {
		this.seen = value;
	}

	/**
	 * Gets the value of the sender property.
	 * 
	 * @return possible object is {@link User }
	 * 
	 */
	public com.projectxml.mojuser.User getSender() {
		return sender;
	}

	/**
	 * Sets the value of the sender property.
	 * 
	 * @param value allowed object is {@link User }
	 * 
	 */
	public void setSender(com.projectxml.mojuser.User value) {
		this.sender = value;
	}

	/**
	 * Gets the value of the reciever property.
	 * 
	 * @return possible object is {@link User }
	 * 
	 */
	public com.projectxml.mojuser.User getReciever() {
		return reciever;
	}

	/**
	 * Sets the value of the reciever property.
	 * 
	 * @param value allowed object is {@link User }
	 * 
	 */
	public void setReciever(com.projectxml.mojuser.User value) {
		this.reciever = value;
	}

	/**
	 * Gets the value of the deleted property.
	 * 
	 */
	public boolean isDeleted() {
		return deleted;
	}

	/**
	 * Sets the value of the deleted property.
	 * 
	 */
	public void setDeleted(boolean value) {
		this.deleted = value;
	}

	/**
	 * Gets the value of the reservation property.
	 * 
	 * @return possible object is {@link Reservation }
	 * 
	 */
	public com.projectxml.reservation.Reservation getReservation() {
		return reservation;
	}

	/**
	 * Sets the value of the reservation property.
	 * 
	 * @param value allowed object is {@link Reservation }
	 * 
	 */
	public void setReservation(com.projectxml.reservation.Reservation value) {
		this.reservation = value;
	}

	/**
	 * Gets the value of the accommodation property.
	 * 
	 * @return possible object is {@link Accommodation }
	 * 
	 */
	public com.projectxml.accommodation.Accommodation getAccommodation() {
		return accommodation;
	}

	/**
	 * Sets the value of the accommodation property.
	 * 
	 * @param value allowed object is {@link Accommodation }
	 * 
	 */
	public void setAccommodation(com.projectxml.accommodation.Accommodation value) {
		this.accommodation = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(Long value) {
		this.id = value;
	}


}
