//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 06:14:21 PM CEST 
//


package com.projectxml.message;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projectxml.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projectxml.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RespondRequest }
     * 
     */
    public RespondRequest createRespondRequest() {
        return new RespondRequest();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link GetMessagesByReservationRequest }
     * 
     */
    public GetMessagesByReservationRequest createGetMessagesByReservationRequest() {
        return new GetMessagesByReservationRequest();
    }

    /**
     * Create an instance of {@link RespondResponse }
     * 
     */
    public RespondResponse createRespondResponse() {
        return new RespondResponse();
    }

    /**
     * Create an instance of {@link GetMessagesByReservationResponse }
     * 
     */
    public GetMessagesByReservationResponse createGetMessagesByReservationResponse() {
        return new GetMessagesByReservationResponse();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

}
