//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 01:15:21 AM CEST 
//

package com.projectxml.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import ftn.xmlws.dto.ReservationDTO;
import ftn.xmlws.miscellaneous.MyTypeConverter;

/**
 * <p>
 * Java class for reservation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="reservation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="confirmed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="agentConfirmed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="guest" type="{http://www.projectXml.com/reservation}user"/>
 *         &lt;element name="fromDateTime" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="toDateTime" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservation", propOrder = { "id", "confirmed", "agentConfirmed", "guest", "fromDateTime",
		"toDateTime" })
public class Reservation {

	protected Long id;
	protected boolean confirmed;
	protected boolean agentConfirmed;
	@XmlElement(required = true)
	protected User guest;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar fromDateTime;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar toDateTime;

	public Reservation() {
	}

	public Reservation(ReservationDTO res) {
		this.id = res.getId();
		this.confirmed = res.isConfirmed();
		this.agentConfirmed = res.isAgentConfirmed();
		this.guest = new User(res.getGuest());
		this.fromDateTime = MyTypeConverter.localDateTimeToXMLGregorianCalendar(res.getFromDateTime());
		this.toDateTime = MyTypeConverter.localDateTimeToXMLGregorianCalendar(res.getToDateTime());
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(Long value) {
		this.id = value;
	}

	/**
	 * Gets the value of the confirmed property.
	 * 
	 */
	public boolean isConfirmed() {
		return confirmed;
	}

	/**
	 * Sets the value of the confirmed property.
	 * 
	 */
	public void setConfirmed(boolean value) {
		this.confirmed = value;
	}

	/**
	 * Gets the value of the agentConfirmed property.
	 * 
	 */
	public boolean isAgentConfirmed() {
		return agentConfirmed;
	}

	/**
	 * Sets the value of the agentConfirmed property.
	 * 
	 */
	public void setAgentConfirmed(boolean value) {
		this.agentConfirmed = value;
	}

	/**
	 * Gets the value of the guest property.
	 * 
	 * @return possible object is {@link User }
	 * 
	 */
	public User getGuest() {
		return guest;
	}

	/**
	 * Sets the value of the guest property.
	 * 
	 * @param value allowed object is {@link User }
	 * 
	 */
	public void setGuest(User value) {
		this.guest = value;
	}

	/**
	 * Gets the value of the fromDateTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFromDateTime() {
		return fromDateTime;
	}

	/**
	 * Sets the value of the fromDateTime property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFromDateTime(XMLGregorianCalendar value) {
		this.fromDateTime = value;
	}

	/**
	 * Gets the value of the toDateTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getToDateTime() {
		return toDateTime;
	}

	/**
	 * Sets the value of the toDateTime property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setToDateTime(XMLGregorianCalendar value) {
		this.toDateTime = value;
	}

}
