//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 07:55:21 PM CEST 
//


package ftn.xmlws.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import ftn.xmlws.dto.ReservationDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="From_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="To_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Confirmed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Comment_rate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Komentar" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Odobren" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="Sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Ocena">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Datum_vreme" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Accommodation_unit"/>
 *         &lt;element name="Guest" type="{http://booking.uns.ac.rs/users}User"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/reservation}Message" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromDate",
    "toDate",
    "confirmed",
    "commentRate",
    "accommodationUnit",
    "guest",
    "id",
    "deleted",
    "messages"
})
@Entity
@XmlRootElement(name = "Reservation", namespace = "http://booking.uns.ac.rs/reservation")
public class Reservation {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlElement(name = "Id", namespace = "http://booking.uns.ac.rs/reservation")
    protected Long id;

	@Transient
    @XmlElement(name = "From_date", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fromDate;
    
	@Transient
    @XmlElement(name = "To_date", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar toDate;
    
	
	@Column(name = "From_date")
	protected LocalDateTime fromDateTime;
	
	@Column(name = "To_date")
	protected LocalDateTime toDateTime;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Guest", namespace = "http://booking.uns.ac.rs/reservation", required = true)
    protected User guest;
    
    @XmlElement(name = "Confirmed", namespace = "http://booking.uns.ac.rs/reservation")
    protected boolean confirmed;
    
    @XmlElement(name = "Agent_confirmed", namespace = "http://booking.uns.ac.rs/reservation")
    protected boolean agentConfirmed;
    
    @XmlElement(name = "Deleted", namespace = "http://booking.uns.ac.rs/reservation")
    protected boolean deleted;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Accommodation_unit", required = true)
    protected AccommodationUnit accommodationUnit;
    
    @XmlElement(name = "Comment_rate", required = true)
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(referencedColumnName="id", nullable = true, unique = true)	
    protected CommentRate commentRate;

    @OneToMany(mappedBy = "reservation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Message", required = true)
    protected List<Message> messages = new ArrayList<>();
    
    protected double price;

    
public Reservation() {}
    
    
    public Reservation(XMLGregorianCalendar fromDate, XMLGregorianCalendar toDate, boolean confirmed) {
		super();
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.confirmed = confirmed;
		this.deleted = false;
	}
    
    public Reservation(ReservationDTO res) {
		super();
		//this.fromDate = MyTypeConverter.localDateToXMLGregorianCalendar(res.getFromDate());
		//this.toDate = MyTypeConverter.localDateToXMLGregorianCalendar(res.getToDate());
		this.fromDateTime = res.getFromDateTime();
		this.toDateTime = res.getToDateTime();
		this.confirmed = res.isConfirmed();
		this.agentConfirmed = res.isAgentConfirmed();
		this.price = res.getPrice();
	}

    
    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setToDate(XMLGregorianCalendar value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     */
    public void setConfirmed(boolean value) {
        this.confirmed = value;
    }

    
    /**
     * Gets the value of the accommodationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationUnit }
     *     
     */
    public AccommodationUnit getAccommodationUnit() {
        return accommodationUnit;
    }

    /**
     * Sets the value of the accommodationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationUnit }
     *     
     */
    public void setAccommodationUnit(AccommodationUnit value) {
        this.accommodationUnit = value;
    }

    /**
     * Gets the value of the guest property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getGuest() {
        return guest;
    }

    /**
     * Sets the value of the guest property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setGuest(User value) {
        this.guest = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }


	public LocalDateTime getFromDateTime() {
		return fromDateTime;
	}


	public void setFromDateTime(LocalDateTime fromDateTime) {
		this.fromDateTime = fromDateTime;
	}


	public LocalDateTime getToDateTime() {
		return toDateTime;
	}


	public void setToDateTime(LocalDateTime toDateTime) {
		this.toDateTime = toDateTime;
	}


    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessages() {
        if (messages == null) {
            messages = new ArrayList<Message>();
        }
        return this.messages;
    }


	public CommentRate getCommentRate() {
		return commentRate;
	}


	public void setCommentRate(CommentRate commentRate) {
		this.commentRate = commentRate;
	}


	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}


	public boolean isAgentConfirmed() {
		return agentConfirmed;
	}


	public void setAgentConfirmed(boolean agentConfirmed) {
		this.agentConfirmed = agentConfirmed;
	}


	public double getPrice() {
		return price;
	}


	public void setPrice(double price) {
		this.price = price;
	}


    
        

}
