//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 03:43:23 PM CEST 
//


package com.projectxml.mojuser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for comment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="comment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentOfComment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="approvedComment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="idReservation" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "comment", propOrder = {
    "contentOfComment",
    "approvedComment",
    "idReservation"
})
public class Comment {

    @XmlElement(required = true)
    protected String contentOfComment;
    protected boolean approvedComment;
    protected long idReservation;

    /**
     * Gets the value of the contentOfComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentOfComment() {
        return contentOfComment;
    }

    /**
     * Sets the value of the contentOfComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentOfComment(String value) {
        this.contentOfComment = value;
    }

    /**
     * Gets the value of the approvedComment property.
     * 
     */
    public boolean isApprovedComment() {
        return approvedComment;
    }

    /**
     * Sets the value of the approvedComment property.
     * 
     */
    public void setApprovedComment(boolean value) {
        this.approvedComment = value;
    }

    /**
     * Gets the value of the idReservation property.
     * 
     */
    public long getIdReservation() {
        return idReservation;
    }

    /**
     * Sets the value of the idReservation property.
     * 
     */
    public void setIdReservation(long value) {
        this.idReservation = value;
    }

}
