//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.25 at 10:49:35 PM CEST 
//


package ftn.xmlws.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Number_of_beds" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Default_price" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Period_price"/&gt;
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Accommodation_unit_type"/&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "floor",
    "number",
    "numberOfBeds",
    "defaultPrice",
    "periodPrice",
    "accommodationUnitType",
    "id"
})
@XmlRootElement(name = "Accommodation_unit")
@Entity
public class AccommodationUnit {

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlElement(name = "Id")
    protected Long id;
	
    @XmlElement(name = "Floor")
    protected int floor;
    
    @XmlElement(name = "Number", required = true)
    protected String number;
    
    @XmlElement(name = "Number_of_beds")
    protected int numberOfBeds;
    
    @XmlElement(name = "Default_price")
    protected Double defaultPrice;
    
    @XmlElement(name = "Deleted")
    protected boolean deleted;
    
    @OneToMany(mappedBy = "accommodationUnit", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Reservation", required = true)
    protected List<Reservation> reservations = new ArrayList<>();
    
    @OneToMany(mappedBy = "accommodationUnit", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @XmlElement(name = "Period_price", required = true)
    protected List<PeriodPrice> periodPrices = new ArrayList<>();
    
    @ManyToOne(fetch = FetchType.LAZY)
    @XmlElement(name = "Accommodation", required = true)
    protected Accommodation accommodation;
    
    @ManyToOne(fetch = FetchType.LAZY)	
    @XmlElement(name = "Accommodation_unit_type", required = true)
    protected AccommodationUnitType accommodationUnitType;
    
    
    public AccommodationUnit() {}

    public AccommodationUnit(int floor, String number, int numberOfBeds, Double defaultPrice) {
		super();
		this.floor = floor;
		this.number = number;
		this.numberOfBeds = numberOfBeds;
		this.defaultPrice = defaultPrice;
	}





	/**
     * Gets the value of the floor property.
     * 
     */
    public int getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     */
    public void setFloor(int value) {
        this.floor = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the numberOfBeds property.
     * 
     */
    public int getNumberOfBeds() {
        return numberOfBeds;
    }

    /**
     * Sets the value of the numberOfBeds property.
     * 
     */
    public void setNumberOfBeds(int value) {
        this.numberOfBeds = value;
    }

    /**
     * Gets the value of the defaultPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDefaultPrice() {
        return defaultPrice;
    }

    /**
     * Sets the value of the defaultPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDefaultPrice(Double value) {
        this.defaultPrice = value;
    }

    /**
     * Gets the value of the periodPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodPrice }
     *     
     */
    public List<PeriodPrice> getPeriodPrices() {
        return periodPrices;
    }

    /**
     * Sets the value of the periodPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodPrice }
     *     
     */
    public void addPeriodPrice(PeriodPrice value) {
        this.periodPrices.add(value);
    }
    
    /**
     * Removes the value of the periodPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodPrice }
     *     
     */
    public void removePeriodPrice(PeriodPrice value) {
        this.periodPrices.remove(value);
    }
    
    

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


	public List<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

	public Accommodation getAccommodation() {
		return accommodation;
	}

	public void setAccommodation(Accommodation accommodation) {
		this.accommodation = accommodation;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setPeriodPrices(List<PeriodPrice> periodPrices) {
		this.periodPrices = periodPrices;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public AccommodationUnitType getAccommodationUnitType() {
		return accommodationUnitType;
	}

	public void setAccommodationUnitType(AccommodationUnitType accommodationUnitType) {
		this.accommodationUnitType = accommodationUnitType;
	}

}
