//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 06:21:28 PM CEST 
//


package ftn.xmlws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Number_of_beds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Default_price" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Period_price"/>
 *         &lt;element ref="{http://booking.uns.ac.rs/accommodation}Accommodation_unit_type"/>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "floor",
    "number",
    "numberOfBeds",
    "defaultPrice",
    "periodPrice",
    "accommodationUnitType",
    "id"
})
@XmlRootElement(name = "Accommodation_unit")
public class AccommodationUnit {

    @XmlElement(name = "Floor")
    protected int floor;
    @XmlElement(name = "Number", required = true)
    protected String number;
    @XmlElement(name = "Number_of_beds")
    protected int numberOfBeds;
    @XmlElement(name = "Default_price")
    protected Double defaultPrice;
    @XmlElement(name = "Period_price", required = true)
    protected PeriodPrice periodPrice;
    @XmlElement(name = "Accommodation_unit_type", required = true)
    protected AccommodationUnitType accommodationUnitType;
    @XmlElement(name = "Id")
    protected long id;

    /**
     * Gets the value of the floor property.
     * 
     */
    public int getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     */
    public void setFloor(int value) {
        this.floor = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the numberOfBeds property.
     * 
     */
    public int getNumberOfBeds() {
        return numberOfBeds;
    }

    /**
     * Sets the value of the numberOfBeds property.
     * 
     */
    public void setNumberOfBeds(int value) {
        this.numberOfBeds = value;
    }

    /**
     * Gets the value of the defaultPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDefaultPrice() {
        return defaultPrice;
    }

    /**
     * Sets the value of the defaultPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDefaultPrice(Double value) {
        this.defaultPrice = value;
    }

    /**
     * Gets the value of the periodPrice property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodPrice }
     *     
     */
    public PeriodPrice getPeriodPrice() {
        return periodPrice;
    }

    /**
     * Sets the value of the periodPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodPrice }
     *     
     */
    public void setPeriodPrice(PeriodPrice value) {
        this.periodPrice = value;
    }

    /**
     * Gets the value of the accommodationUnitType property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationUnitType }
     *     
     */
    public AccommodationUnitType getAccommodationUnitType() {
        return accommodationUnitType;
    }

    /**
     * Sets the value of the accommodationUnitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationUnitType }
     *     
     */
    public void setAccommodationUnitType(AccommodationUnitType value) {
        this.accommodationUnitType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

}
