//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 06:21:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://booking.uns.ac.rs/accommodation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ftn.xmlws.model;
