//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 06:59:42 PM CEST 
//


package com.projectxml.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.projectxml.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.projectxml.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddAccommodationServiceRequest }
     * 
     */
    public AddAccommodationServiceRequest createAddAccommodationServiceRequest() {
        return new AddAccommodationServiceRequest();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link GetAccommodationServicesResponse }
     * 
     */
    public GetAccommodationServicesResponse createGetAccommodationServicesResponse() {
        return new GetAccommodationServicesResponse();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link GetServicesRequest }
     * 
     */
    public GetServicesRequest createGetServicesRequest() {
        return new GetServicesRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationServicesRequest }
     * 
     */
    public GetAccommodationServicesRequest createGetAccommodationServicesRequest() {
        return new GetAccommodationServicesRequest();
    }

    /**
     * Create an instance of {@link RemoveAccommodationServiceRequest }
     * 
     */
    public RemoveAccommodationServiceRequest createRemoveAccommodationServiceRequest() {
        return new RemoveAccommodationServiceRequest();
    }

    /**
     * Create an instance of {@link RemoveServiceRequest }
     * 
     */
    public RemoveServiceRequest createRemoveServiceRequest() {
        return new RemoveServiceRequest();
    }

    /**
     * Create an instance of {@link GetServiceResponse }
     * 
     */
    public GetServiceResponse createGetServiceResponse() {
        return new GetServiceResponse();
    }

    /**
     * Create an instance of {@link GetServiceRequest }
     * 
     */
    public GetServiceRequest createGetServiceRequest() {
        return new GetServiceRequest();
    }

    /**
     * Create an instance of {@link AddServiceResponse }
     * 
     */
    public AddServiceResponse createAddServiceResponse() {
        return new AddServiceResponse();
    }

    /**
     * Create an instance of {@link GetServicesResponse }
     * 
     */
    public GetServicesResponse createGetServicesResponse() {
        return new GetServicesResponse();
    }

    /**
     * Create an instance of {@link AddServiceRequest }
     * 
     */
    public AddServiceRequest createAddServiceRequest() {
        return new AddServiceRequest();
    }

    /**
     * Create an instance of {@link UpdateServiceRequest }
     * 
     */
    public UpdateServiceRequest createUpdateServiceRequest() {
        return new UpdateServiceRequest();
    }

    /**
     * Create an instance of {@link AddAccommodationServiceResponse }
     * 
     */
    public AddAccommodationServiceResponse createAddAccommodationServiceResponse() {
        return new AddAccommodationServiceResponse();
    }

}
